###
POST http://localhost:3333/accounts
Content-Type: application/json

{
  "name": "My account"
}

###
PATCH http://localhost:3333/accounts/384d6f3b-ebd6-46b3-ac53-474f3c8b571b
Content-Type: application/json

{
  "name": "My account update"
}

###
DELETE http://localhost:3333/accounts/384d6f3b-ebd6-46b3-ac53-474f3c8b571b

###
GET http://localhost:3333/accounts/384d6f3b-ebd6-46b3-ac53-474f3c8b571b

###
GET http://localhost:3333/accounts



### credit card valid
POST http://localhost:3333/orders
Content-Type: application/json
x-token: 8fbfdbf66y8

{
  "amount": 16.90,
  "credit_card_name": "John Doe",
  "credit_card_number": "4193523830170205"
}

### credit card invalid
POST http://localhost:3333/orders
Content-Type: application/json
x-token: 8fbfdbf66y8

{
  "amount": 16.90,
  "credit_card_name": "John Doe",
  "credit_card_number": "4000000000000000"
}

###
PATCH http://localhost:3333/orders/1815b571-2fdb-45b4-9487-1778f9f300d7
Content-Type: application/json
x-token: 8fbfdbf66y8

{
  "amount": 26.90
}

###
DELETE http://localhost:3333/orders/1815b571-2fdb-45b4-9487-1778f9f300d7
x-token: 8fbfdbf66y8

###
GET http://localhost:3333/orders/1815b571-2fdb-45b4-9487-1778f9f300d7
x-token: 8fbfdbf66y8

###
GET http://localhost:3333/orders
x-token: 8fbfdbf66y8
