###
POST {{api_url}}/accounts
Content-Type: application/json

{
  "name": "My account"
}

###
PATCH {{api_url}}/accounts/{{account_id}}
Content-Type: application/json

{
  "name": "My account update"
}

###
DELETE {{api_url}}/accounts/{{account_id}}

###
GET {{api_url}}/accounts/{{account_id}}

###
GET {{api_url}}/accounts



### credit card valid
POST {{api_url}}/orders
Content-Type: application/json
x-token: {{x_token}}

{
  "amount": 16.90,
  "credit_card_name": "John Doe",
  "credit_card_number": "4193523830170205",
  "credit_card_expiration_month": 12,
  "credit_card_expiration_year": 2022,
  "credit_card_cvv": 123
}

### credit card invalid
POST {{api_url}}/orders
Content-Type: application/json
x-token: {{x_token}}

{
  "amount": 16.90,
  "credit_card_name": "John Doe",
  "credit_card_number": "4000000000000000",
  "credit_card_expiration_month": 12,
  "credit_card_expiration_year": 2022,
  "credit_card_cvv": 123
}

###
PATCH {{api_url}}/orders/{{order_id}}
Content-Type: application/json
x-token: {{x_token}}

{
  "amount": 26.90
}

###
DELETE {{api_url}}/orders/{{order_id}}
x-token: {{x_token}}

###
GET {{api_url}}/orders/{{order_id}}
x-token: {{x_token}}

###
GET {{api_url}}/orders
x-token: {{x_token}}
