version: "3"

services:
  app:
    build: .
    container_name: codepay-backend-app
    entrypoint: wait-for db:3306 -t 40 -- ./.docker/entrypoint.sh
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: ./.docker/mysql
    command: --innodb-use-native-aio=0
    container_name: codepay-backend-db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql/initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
